version: "3"

services:
  spark-iceberg:
    image: tabulario/spark-iceberg:local
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
networks:
  iceberg_net: